### ISSUE TITLE
Handle exception when trying to create a changelog file in a non-git directory

### ISSUE THREAD

**Issue by ghost** [jeroenouw/cgx#7]
**Describe the bug**
Exception is raised when user tries to create Changelog file in a directory without Git initialised.

**To Reproduce**
1. Run cgx
2. Select any provider
3. Scroll down to Changelog

```
fatal: not a git repository (or any of the parent directories): .git
(node:4920) UnhandledPromiseRejectionWarning: Error: Command failed: git log --pretty=format:"%h%n%d%n%an%n%s%n%ai%n%b%ae%n%n" --no-merges -z
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at Changelog.generateFileContent (C:\Users\joaos\AppData\Roaming\npm\node_modules\cgx\lib\templates\universal\changelog.template.js:17:35)
    at Changelog.generateFile (C:\Users\joaos\AppData\Roaming\npm\node_modules\cgx\lib\templates\universal\changelog.template.js:13:63)
    at GithubActions.<anonymous> (C:\Users\joaos\AppData\Roaming\npm\node_modules\cgx\lib\actions\github.actions.js:43:70)
    at step (C:\Users\joaos\AppData\Roaming\npm\node_modules\cgx\node_modules\tslib\tslib.js:136:27)
    at Object.next (C:\Users\joaos\AppData\Roaming\npm\node_modules\cgx\node_modules\tslib\tslib.js:117:57)
    at fulfilled (C:\Users\joaos\AppData\Roaming\npm\node_modules\cgx\node_modules\tslib\tslib.js:107:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
In a directory iwthout a `.git` subdirectory, `cgx` must show an error message like `This is not a Git repository` and exit.

**Desktop (please complete the following information):**
    - OS: Windows 10 v2004 build 19041.21

**Comment by jeroenouw** [comment]
@joaosantana; @farisT created PR in #9
